server:
  port: 8080
spring:
    datasource:
        name: lifewater
        #一定带上编码设置，不然会乱码
        url: jdbc:mysql://192.168.1.108:3306/lifewater?useUnicode=true&characterEncoding=UTF-8
        username: LIFEWATER
        password: LIFEWATER
        # druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    thymeleaf:
          model: HTML5
          servlet:
            content-type: text/html
          encoding: utf-8
          #开发时关闭缓存,不然没法看到实时页面
          cache: false
          prefix: classpath:/templates/
          suffix: .html
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wade.lifewater.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
    com.wade.lifewater.mapper: DEBUG